"""Provenance: where every number on this screen comes from.

Two questions a judge asks that a diagram cannot answer: what is the data, and
is any of it actually moving. This page answers the first with measured facts
(systems, row counts, spans, staleness, the exact SQL) and the second with a
live ingestion lane written by a separate process.
"""
import pandas as pd
import streamlit as st

from engine import db, retrieve, sources
from services import live_ingest
from ui.common import C, fmt, section_label, stat_tile


def render(ctx):
    role_id = ctx.viewer.role_id

    st.header("Where the data comes from")
    st.caption("Every figure in this app traces back through this page: a named "
               "source system, a governed SQL definition, and the rows it touched. "
               "Nothing is hand-entered, and nothing is produced by the model.")

    # ---------------------------------------------------------------- sources
    section_label("Source systems, measured rather than declared")
    stats = db.source_stats(role_id)
    for col, (_table, s) in zip(st.columns(len(stats)), stats.items()):
        col.markdown(stat_tile(s["system"].split(" (")[0], f"{s['rows']:,}",
                               chip=s["grain"], sub=f"through {s['last']}",
                               accent=C["series"]), unsafe_allow_html=True)
    st.dataframe(pd.DataFrame([
        {"system": s["system"], "table": t, "kind": s.get("kind", ""),
         "status": s.get("status", ""), "grain": s["grain"],
         "declared refresh": s["refresh"], "rows": s["rows"],
         "earliest": s["first"], "latest": s["last"]}
        for t, s in stats.items()]), hide_index=True, width="stretch")
    prov = db.source_provenance()
    summ = sources.summary(prov)
    st.caption(f"Reconciled across **{summ['systems']} systems** in "
               f"**{len(summ['kinds'])} formats** ({', '.join(summ['kinds'])}): "
               f"{summ['live']} fetched live, {summ['extract']} from a last extract, "
               f"{summ['file']} from scheduled extract files. A live source that cannot "
               "be reached falls back to its extract and says so here; nothing is "
               "substituted silently.")
    for p_ in prov:
        if p_["status"] in ("live", "extract"):
            st.caption(f"{p_['system']}: **{p_['status']}** · {p_['note']}"
                       + (f" · fetched {p_['fetched_at']}" if p_.get("fetched_at") else ""))
    st.caption(f"Row counts are what **{role_id}** can see: the row filter applies "
               "here too, so this page describes the system as it exists for the "
               "signed-in role rather than in the abstract.")
    st.caption("This is a **synthetic** dataset generated by `data/generate_data.py` "
               "with known causes planted in it. That is deliberate: it is the only "
               "reason the evaluation panel can quote a precision and a recall at "
               "all. Real client data arrives without an answer key.")
    info = db.backend_info()
    engine_label = {"duckdb": "DuckDB", "postgresql": "PostgreSQL"}.get(info["backend"], info["backend"])
    st.caption(f"Analytics engine: **{engine_label}** · `{info['detail']}` · the same "
               "contract SQL runs on DuckDB or PostgreSQL; `RATIONALE_DB` selects which.")

    # ------------------------------------------------------------- the chain
    section_label("The chain behind one KPI")
    kpis = db.allowed_kpis(role_id)
    pick = st.selectbox("KPI", list(kpis), format_func=lambda k: kpis[k]["name"],
                        key="lineage_kpi")
    lin = db.kpi_lineage(pick, role_id)
    left, right = st.columns([1, 1])
    with left:
        st.markdown(
            "<div style='font-family:monospace;font-size:0.86rem;line-height:2.0;"
            f"color:{C['ink']}'>"
            f"<b>{lin['system']}</b><br>"
            f"&nbsp;&nbsp;&#8595; loaded into {engine_label} as <code>{lin['source']}</code><br>"
            "&nbsp;&nbsp;&#8595; governed SQL from the semantic contract<br>"
            f"&nbsp;&nbsp;&#8595; row filter for <b>{role_id}</b><br>"
            f"&nbsp;&nbsp;&#8595; anomaly test vs |z| &ge; "
            f"{lin['materiality'].get('min_abs_z')}<br>"
            "&nbsp;&nbsp;&#8595; multiplicity control across the portfolio<br>"
            f"<b>{lin['name']}</b></div>", unsafe_allow_html=True)
    with right:
        st.caption(f"Owner of record: **{lin['owner']}**")
        st.caption("Broken down by: " + (", ".join(lin["dimensions"]) or "—"))
        st.caption("Declared drivers: "
                   + (", ".join(lin["drivers"]) or "none declared for this KPI"))
    st.caption("The exact statement executed for this role. The row filter is inside "
               "the query, not applied afterwards in the UI:")
    st.code(lin["sql"], language="sql")

    # ----------------------------------------------------------- the corpus
    section_label("Unstructured context")
    corpus = retrieve.load_corpus()
    docs = [d for d in corpus if d["kind"] == "document"]
    ledger = [d for d in corpus if d["kind"] == "ledger"]
    c1, c2 = st.columns(2)
    c1.markdown(stat_tile("Source documents", str(len(docs)),
                          sub="tickets, transcripts, ops notes, postmortems",
                          accent=C["series"]), unsafe_allow_html=True)
    c2.markdown(stat_tile("Past conclusions", str(len(ledger)),
                          sub="the decision ledger, used as precedent",
                          accent=C["ink2"]), unsafe_allow_html=True)
    st.caption("Two of the documents are deliberate red herrings. Retrieval is "
               "whole-term weighted matching; precedent is only admissible from "
               "periods strictly before the one being analysed.")

    # --------------------------------------------------------- the live lane
    section_label("Live ingestion, from a second process")
    stat = live_ingest.status()
    if not stat:
        st.info("No live ingestion running. Start it in a second terminal:\n\n"
                "```\npython -m ops.ingest --rate 2 --inject-anomaly 40\n```\n\n"
                "The Live Feed page replays rows that were already in the dataset. "
                "That shows the detector working, but it does not show the "
                "ingestion path is real. This does: another process appends events "
                "now, and the same rolling rule picks them up here.")
        return

    v = live_ingest.verdict()
    s1, s2, s3 = st.columns(3)
    s1.markdown(stat_tile("Events ingested", f"{stat.get('events', 0):,}",
                          sub=f"since {str(stat.get('started', ''))[11:] or '—'}",
                          accent=C["good"]), unsafe_allow_html=True)
    s2.markdown(stat_tile("Last event", str(stat.get("last", ""))[11:] or "—",
                          sub=f"~{stat.get('rate_per_s', 0)}/s from ops/ingest.py",
                          accent=C["series"]), unsafe_allow_html=True)
    s3.markdown(stat_tile("Live verdict",
                          ", ".join(v["breached"]) if v["breached"] else "all normal",
                          sub=f"trailing {v.get('window', 0)} events",
                          accent=C["critical"] if v["breached"] else C["good"]),
                unsafe_allow_html=True)

    if not v["assessable"]:
        st.caption(v.get("note", "waiting for enough events"))
    else:
        tbl = pd.DataFrame(v["regions"])[["region", "events", "shipments",
                                          "breaches", "breach_rate", "revenue"]]
        tbl["breach_rate"] = (tbl["breach_rate"] * 100).round(1)
        tbl["revenue"] = tbl["revenue"].map(lambda x: fmt(x, "INR"))
        st.dataframe(tbl.rename(columns={"breach_rate": "SLA breach %"}),
                     hide_index=True, width="stretch")

    if v["breached"]:
        st.markdown(
            f"<div style='padding:10px 14px;border-left:3px solid {C['critical']};"
            f"background:{C['critical']}14;color:{C['ink']};font-weight:600'>"
            f"Live breach in {', '.join(v['breached'])} — found in data that did not "
            "exist when this page loaded.</div>", unsafe_allow_html=True)

    st.caption("Written to its own lane (`data/live/`) rather than into the demo "
               "tables: mutating those mid-demo would move the recorded numbers and "
               "invalidate the fixtures. Refresh the page to poll.")
